version: "3"
services:
  proxy:
    image: ubuntu/squid:5.2-22.04_beta
    ports:
      - "8080:3128"
    volumes:
      - ./logs:/var/log/squid
      - ./data:/var/spool/squid
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
    restart: always
